ALTER TABLE loans ADD COLUMN IF NOT EXISTS najiz_plaintiff_name VARCHAR(255);
ALTER TABLE loans ADD COLUMN IF NOT EXISTS najiz_plaintiff_national_id VARCHAR(20);
ALTER TABLE loans ADD COLUMN IF NOT EXISTS najiz_raised_date TIMESTAMP WITHOUT TIME ZONE;
