ALTER TABLE customers ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
ALTER TABLE merchant_employees ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
